# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventStoreModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'initial_state': 'dict(str, str)',
        'initial_state_hash': 'str',
        'initial_state_timestamp': 'datetime',
        'events': 'list[Event]'
    }

    attribute_map = {
        'initial_state': 'initial_state',
        'initial_state_hash': 'initial_state_hash',
        'initial_state_timestamp': 'initial_state_timestamp',
        'events': 'events'
    }

    def __init__(self, initial_state=None, initial_state_hash=None, initial_state_timestamp=None, events=None):  # noqa: E501
        """EventStoreModel - a model defined in Swagger"""  # noqa: E501
        self._initial_state = None
        self._initial_state_hash = None
        self._initial_state_timestamp = None
        self._events = None
        self.discriminator = None
        if initial_state is not None:
            self.initial_state = initial_state
        if initial_state_hash is not None:
            self.initial_state_hash = initial_state_hash
        if initial_state_timestamp is not None:
            self.initial_state_timestamp = initial_state_timestamp
        if events is not None:
            self.events = events

    @property
    def initial_state(self):
        """Gets the initial_state of this EventStoreModel.  # noqa: E501


        :return: The initial_state of this EventStoreModel.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._initial_state

    @initial_state.setter
    def initial_state(self, initial_state):
        """Sets the initial_state of this EventStoreModel.


        :param initial_state: The initial_state of this EventStoreModel.  # noqa: E501
        :type: dict(str, str)
        """

        self._initial_state = initial_state

    @property
    def initial_state_hash(self):
        """Gets the initial_state_hash of this EventStoreModel.  # noqa: E501


        :return: The initial_state_hash of this EventStoreModel.  # noqa: E501
        :rtype: str
        """
        return self._initial_state_hash

    @initial_state_hash.setter
    def initial_state_hash(self, initial_state_hash):
        """Sets the initial_state_hash of this EventStoreModel.


        :param initial_state_hash: The initial_state_hash of this EventStoreModel.  # noqa: E501
        :type: str
        """

        self._initial_state_hash = initial_state_hash

    @property
    def initial_state_timestamp(self):
        """Gets the initial_state_timestamp of this EventStoreModel.  # noqa: E501


        :return: The initial_state_timestamp of this EventStoreModel.  # noqa: E501
        :rtype: datetime
        """
        return self._initial_state_timestamp

    @initial_state_timestamp.setter
    def initial_state_timestamp(self, initial_state_timestamp):
        """Sets the initial_state_timestamp of this EventStoreModel.


        :param initial_state_timestamp: The initial_state_timestamp of this EventStoreModel.  # noqa: E501
        :type: datetime
        """

        self._initial_state_timestamp = initial_state_timestamp

    @property
    def events(self):
        """Gets the events of this EventStoreModel.  # noqa: E501


        :return: The events of this EventStoreModel.  # noqa: E501
        :rtype: list[Event]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this EventStoreModel.


        :param events: The events of this EventStoreModel.  # noqa: E501
        :type: list[Event]
        """

        self._events = events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventStoreModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventStoreModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
